Fix literal error printf lines
Signed-off-by: Alec Ari <neotheuser@ymail.com>

diff --git a/toolchain_builder b/toolchain_builder
--- a/toolchain_builder
+++ b/toolchain_builder
@@ -49,7 +49,7 @@ fi
 # i.e. #define X_Y_Z 1 (for true) therefor NOT a typo
 
 # Reduce lengthly printf lines
-REPORT_BUG_EXIT="\\n\\tPlease report bug to script maintainer.\\n\\tExiting.\\n"
+REPORT_BUG_EXIT="Please report bug to script maintainer. Exiting."
 
 #
 # User configuation:
@@ -265,7 +265,7 @@ else
 			fi
 		fi
 	else
-		printf "\\tError detecting git version.%s" "${REPORT_BUG_EXIT}"
+		printf "\\tError detecting git version.\\n\\t%s\\n" "${REPORT_BUG_EXIT}"
 	fi
 
 # Only x86/amd64 are supported due to GCC hard links
@@ -310,7 +310,7 @@ else
 \\tplease report your success, your feedback is greatly appreciated.\\n"
 			exit 1
 		else
-			printf "\\tError detecting the build environment.%s" "${REPORT_BUG_EXIT}"
+			printf "\\tError detecting the build environment.\\n\\t%s\\n" "${REPORT_BUG_EXIT}"
 			exit 1
 		fi
 	else
@@ -330,7 +330,7 @@ fi
 			exit 1
 		fi
 	else
-		printf "\\tError processing config file.%s" "${REPORT_BUG_EXIT}"
+		printf "\\tError processing config file.\\n\\t%s\\n" "${REPORT_BUG_EXIT}"
 		exit 1
 	fi
 	printf "\\tAssuming everything else is ok.\\n"
@@ -453,7 +453,7 @@ fetch_sources ()
 {
 	cd "${TOOLCHAIN_SRCDIR}" || \
 	{
-		printf "\\tError changing directory to %s.%s" \
+		printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 		"${TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
@@ -584,49 +584,49 @@ verify_sources ()
 
 	test -d "${LINUX_TOOLCHAIN_SRCDIR}" || \
 	{
-		printf "\\tUnexpected error: %s cannot be found.%s" \
+		printf "\\tUnexpected error: %s cannot be found.\\n\\t%s\\n" \
 		"${LINUX_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
 	test -d "${GMP_TOOLCHAIN_SRCDIR}" || \
 	{
-		printf "\\tUnexpected error: %s cannot be found.%s" \
+		printf "\\tUnexpected error: %s cannot be found.\\n\\t%s\\n" \
 		"${GMP_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
 	test -d "${MPFR_TOOLCHAIN_SRCDIR}" || \
 	{
-		printf "\\tUnexpected error: %s cannot be found.%s" \
+		printf "\\tUnexpected error: %s cannot be found.\\n\\t%s\\n" \
 		"${MPFR_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
 	test -d "${MPC_TOOLCHAIN_SRCDIR}" || \
 	{
-		printf "\\tUnexpected error: %s cannot be found.%s" \
+		printf "\\tUnexpected error: %s cannot be found.\\n\\t%s\\n" \
 		"${MPC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
 	test -d "${ISL_TOOLCHAIN_SRCDIR}" || \
 	{
-		printf "\\tUnexpected error: %s cannot be found.%s" \
+		printf "\\tUnexpected error: %s cannot be found.\\n\\t%s\\n" \
 		"${ISL_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
 	test -d "${BINUTILS_TOOLCHAIN_SRCDIR}" || \
 	{
-		printf "\\tUnexpected error: %s cannot be found.%s" \
+		printf "\\tUnexpected error: %s cannot be found.\\n\\t%s\\n" \
 		"${BINUTILS_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
 	test -d "${GLIBC_TOOLCHAIN_SRCDIR}" || \
 	{
-		printf "\\tUnexpected error: %s cannot be found.%s" \
+		printf "\\tUnexpected error: %s cannot be found.\\n\\t%s\\n" \
 		"${GLIBC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
 	test -d "${GCC_TOOLCHAIN_SRCDIR}" || \
 	{
-		printf "\\tUnexpected error: %s cannot be found.%s" \
+		printf "\\tUnexpected error: %s cannot be found.\\n\\t%s\\n" \
 		"${GCC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
@@ -648,7 +648,7 @@ update_binutils ()
 
 	cd "${BINUTILS_TOOLCHAIN_SRCDIR}" || \
 	{
-		printf "\\tError changing directory to %s.%s" \
+		printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 		"${BINUTILS_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
@@ -663,7 +663,7 @@ update_glibc ()
 
 	cd "${GLIBC_TOOLCHAIN_SRCDIR}" || \
 	{
-		printf "\\tError changing directory to %s.%s" \
+		printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 		"${GLIBC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
@@ -678,7 +678,7 @@ update_gcc ()
 
 	cd "${GCC_TOOLCHAIN_SRCDIR}" || \
 	{
-		printf "\\tError changing directory to %s.%s" \
+		printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 		"${GCC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
@@ -694,7 +694,7 @@ if [[ -d "${BINUTILS_TOOLCHAIN_SRCDIR}" && -d "${GLIBC_TOOLCHAIN_SRCDIR}" && -d 
 	update_glibc
 	update_gcc
 else
-	printf "\\n\\tUnexpected error: Cannot find git sources.%s" "${REPORT_BUG_EXIT}"
+	printf "\\n\\tUnexpected error: Cannot find git sources.\\n\\t%s\\n" "${REPORT_BUG_EXIT}"
 	exit 1
 fi
 }
@@ -755,7 +755,7 @@ if [[ "${ARCH_UNAME}" == *64 ]] ; then
 
 		mkdir -p "${TOOLCHAIN_BINDIR}"/usr/lib64 || \
 		{
-			printf "\\tError creating ${TOOLCHAIN_BINDIR}/usr/lib64.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+			printf "\\tError creating ${TOOLCHAIN_BINDIR}/usr/lib64.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 
 		printf "\\tSetting TOOLCHAIN_LIBDIR...\\n"
@@ -769,7 +769,7 @@ elif [[ ${ARCH_UNAME} == *86 ]] ; then
 
 		mkdir -p "${TOOLCHAIN_BINDIR}"/usr/lib || \
 		{
-			printf "\\tError creating ${TOOLCHAIN_BINDIR}/usr/lib.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+			printf "\\tError creating ${TOOLCHAIN_BINDIR}/usr/lib.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 
 		printf "\\tSetting TOOLCHAIN_LIBDIR...\\n"
@@ -794,7 +794,7 @@ if [[ ! -d "${BINUTILS_TOOLCHAIN_SRCDIR}"/gmp ]] ; then
 
 	cp -pr "${GMP_TOOLCHAIN_SRCDIR}" "${BINUTILS_TOOLCHAIN_SRCDIR}"/ || \
 	{
-		printf "\\tError copying GMP to Binutils.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tError copying GMP to Binutils.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 fi
 
@@ -803,7 +803,7 @@ if [[ ! -d ${BINUTILS_TOOLCHAIN_SRCDIR}/mpfr ]] ; then
 
 	cp -pr "${MPFR_TOOLCHAIN_SRCDIR}" "${BINUTILS_TOOLCHAIN_SRCDIR}"/ || \
 	{
-		printf "\\tError copying MPFR to Binutils.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tError copying MPFR to Binutils.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 fi
 
@@ -812,7 +812,7 @@ if [[ ! -d ${BINUTILS_TOOLCHAIN_SRCDIR}/mpc ]] ; then
 
 	cp -pr "${MPC_TOOLCHAIN_SRCDIR}" "${BINUTILS_TOOLCHAIN_SRCDIR}"/ || \
 	{
-		printf "\\tError copying MPC to Binutils.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tError copying MPC to Binutils.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 fi
 
@@ -821,7 +821,7 @@ if [[ ! -d ${BINUTILS_TOOLCHAIN_SRCDIR}/isl ]] ; then
 
 	cp -pr "${ISL_TOOLCHAIN_SRCDIR}" "${BINUTILS_TOOLCHAIN_SRCDIR}"/ || \
 	{
-		printf "\\tError copying ISL to Binutils.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tError copying ISL to Binutils.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 fi
 }
@@ -849,17 +849,17 @@ elif [[ $(grep -c "${TOOLCHAIN_LIBDIR}" "${X86_64_LDCONFIG}") == 0 ]] ; then
 
 	sed "s#/lib/ld-linux.so.2#${TOOLCHAIN_LIBDIR}/ld-linux.so.2#g" -i "${X86_64_LDCONFIG}" || \
 	{
-		printf "\\tApplying 32-bit hard code fix failed.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tApplying 32-bit hard code fix failed.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
 	sed "s#/lib64/ld-linux-x86-64.so.2#${TOOLCHAIN_LIBDIR}/ld-linux-x86-64.so.2#g" -i "${X86_64_LDCONFIG}" || \
 	{
-		printf "\\tApplying 64-bit hard code fix failed.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tApplying 64-bit hard code fix failed.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
 	printf "\\tGLIBC hard code fix now applied.\\n"
 else
-	printf "\\tError detecting if GLIBC is hard coded.%s" "${REPORT_BUG_EXIT}"
+	printf "\\tError detecting if GLIBC is hard coded.\\n\\t%s\\n" "${REPORT_BUG_EXIT}"
 	exit 1
 fi
 }
@@ -889,19 +889,19 @@ if [[ ${PIC_CONF_NUM} == 1 && ${PIC_CONF_AC_NUM} == 1 ]] ; then
 	printf "\\tlibstdc++-v3 PIC patch not applied. Applying...\\n"
 
 	cd "${GLIBC_TOOLCHAIN_SRCDIR}" || \
-	printf "\\tError changing directory to %s.%s" \
+	printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 	"${GLIBC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" \
 	exit 1
 
 	patch -p1 < "${GCC_PIC_PATCH}" || \
 	{
-		printf "\\tlibstdc++-v3 PIC patch failed.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tlibstdc++-v3 PIC patch failed.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
 elif [[ "${PIC_CONF_NUM}" == 2 && "${PIC_CONF_AC_NUM}" == 2 ]] ; then
 	printf "\\tlibstdc++-v3 PIC patch already applied.\\n"
 else
-	printf "\\tgcc/libstdc++-v3 patch failed.%s" "${REPORT_BUG_EXIT}"
+	printf "\\tgcc/libstdc++-v3 patch failed.\\n\\t%s\\n" "${REPORT_BUG_EXIT}"
 	exit 1
 fi
 }
@@ -922,12 +922,12 @@ elif [[ $(grep -c "${TOOLCHAIN_LIBDIR}" "${GCC_CONF_32_H}") == 0 ]] ; then
 
 	sed "s#/lib/ld-linux.so.2#${TOOLCHAIN_LIBDIR}/ld-linux.so.2#g" -i "${GCC_CONF_32_H}" || \
 	{
-		printf "\\tApplying 32-bit linker fix failed.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tApplying 32-bit linker fix failed.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
 	printf "\\t32-bit GCC linker fix now applied.\\n"
 else
-	printf "\\tError detecting if GCC is using proper linker.%s" "${REPORT_BUG_EXIT}"
+	printf "\\tError detecting if GCC is using proper linker.\\n\\t%s\\n" "${REPORT_BUG_EXIT}"
 	exit 1
 fi
 
@@ -940,17 +940,17 @@ elif [[ $(grep -c "${TOOLCHAIN_LIBDIR}" "${GCC_CONF_64_H}") == 0 ]] ; then
 
 	sed "s#/lib64/ld-linux-x86-64.so.2#${TOOLCHAIN_LIBDIR}/ld-linux-x86-64.so.2#g" -i "${GCC_CONF_64_H}" || \
 	{
-		printf "\\tApplying 64-bit linker fix failed.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tApplying 64-bit linker fix failed.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
 	sed "s#/lib/ld-linux.so.2#${TOOLCHAIN_LIBDIR}/ld-linux.so.2#g" -i "${GCC_CONF_64_H}" || \
 	{
-		printf "\\tApplying 64-bit linker fix failed.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tApplying 64-bit linker fix failed.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
 	printf "\\t64-bit GCC linker fix now applied.\\n"
 else
-	printf "\\tError detecting if GCC is using proper linker.%s" "${REPORT_BUG_EXIT}"
+	printf "\\tError detecting if GCC is using proper linker.\\n\\t%s\\n" "${REPORT_BUG_EXIT}"
 	exit 1
 fi
 }
@@ -966,7 +966,7 @@ if [[ ! -d "${GCC_TOOLCHAIN_SRCDIR}"/gmp ]] ; then
 
 	cp -pr "${GMP_TOOLCHAIN_SRCDIR}" "${GCC_TOOLCHAIN_SRCDIR}"/ || \
 	{
-		printf "\\tError copying GMP to GCC.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tError copying GMP to GCC.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 fi
 
@@ -975,7 +975,7 @@ if [[ ! -d "${GCC_TOOLCHAIN_SRCDIR}"/mpfr ]] ; then
 
 	cp -pr "${MPFR_TOOLCHAIN_SRCDIR}" "${GCC_TOOLCHAIN_SRCDIR}"/ || \
 	{
-		printf "\\tError copying MPFR to GCC.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tError copying MPFR to GCC.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 fi
 
@@ -984,7 +984,7 @@ if [[ ! -d "${GCC_TOOLCHAIN_SRCDIR}"/mpc ]] ; then
 
 	cp -pr "${MPC_TOOLCHAIN_SRCDIR}" "${GCC_TOOLCHAIN_SRCDIR}"/ || \
 	{
-		printf "\\tError copying MPC to GCC.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tError copying MPC to GCC.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 fi
 
@@ -993,7 +993,7 @@ if [[ ! -d "${GCC_TOOLCHAIN_SRCDIR}"/isl ]] ; then
 
 	cp -pr "${ISL_TOOLCHAIN_SRCDIR}" "${GCC_TOOLCHAIN_SRCDIR}"/ || \
 	{
-		printf "\\tError copying ISL to GCC.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		printf "\\tError copying ISL to GCC.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 fi
 }
@@ -1014,7 +1014,7 @@ install_linux_headers ()
 
 	cd "${LINUX_TOOLCHAIN_SRCDIR}" || \
 	{
-		printf "\\tError changing directory to %s.%s" \
+		printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 		"${LINUX_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
@@ -1059,7 +1059,7 @@ first_pass_binutils ()
 
 		cd "${BINUTILS_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError changing directory to %s.%s" \
+			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${BINUTILS_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 
@@ -1068,13 +1068,13 @@ first_pass_binutils ()
 	else
 		mkdir -p "${BINUTILS_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError creating %s.%s" \
+			printf "\\tError creating %s.\\n\\t%s\\n" \
 			"${BINUTILS_TOOLCHAIN_SRCDIR}"/build "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 
 		cd "${BINUTILS_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError changing directory to %s.%s" \
+			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${BINUTILS_TOOLCHAIN_SRCDIR}"/build "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 	fi
@@ -1121,7 +1121,7 @@ first_pass_glibc ()
 
 		cd "${GLIBC_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError changing directory to %s.%s" \
+			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${GLIBC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 		exit 1
@@ -1131,13 +1131,13 @@ first_pass_glibc ()
 	else
 		mkdir -p "${GLIBC_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError creating %s.%s" \
+			printf "\\tError creating %s.\\n\\t%s\\n" \
 			"${GLIBC_TOOLCHAIN_SRCDIR}"/build "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 
 		cd "${GLIBC_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError changing directory to %s.%s" \
+			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${GLIBC_TOOLCHAIN_SRCDIR}"/build "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 	fi
@@ -1181,7 +1181,7 @@ first_pass_gcc ()
 
 		cd "${GCC_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError changing directory to %s.%s" \
+			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${GCC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 		exit 1
@@ -1191,13 +1191,13 @@ first_pass_gcc ()
 	else
 		mkdir -p "${GCC_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError creating %s.%s" \
+			printf "\\tError creating %s.\\n\\t%s\\n" \
 			"${GCC_TOOLCHAIN_SRCDIR}"/build "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 
 		cd "${GCC_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError changing directory to %s.%s" \
+			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${GCC_TOOLCHAIN_SRCDIR}"/build "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 	fi
@@ -1277,7 +1277,7 @@ second_pass_binutils ()
 
 		cd "${BINUTILS_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError changing directory to %s.%s" \
+			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${BINUTILS_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 		exit 1
@@ -1287,13 +1287,13 @@ second_pass_binutils ()
 	else
 		mkdir -p "${BINUTILS_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError creating %s.%s" \
+			printf "\\tError creating %s.\\n\\t%s\\n" \
 			"${BINUTILS_TOOLCHAIN_SRCDIR}"/build "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 
 		cd "${BINUTILS_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError changing directory to %s.%s" \
+			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${BINUTILS_TOOLCHAIN_SRCDIR}"/build "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 	fi
@@ -1355,7 +1355,7 @@ second_pass_glibc ()
 
 		cd "${GLIBC_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError changing directory to %s.%s" \
+			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${GLIBC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 
@@ -1364,13 +1364,13 @@ second_pass_glibc ()
 	else
 		mkdir -p "${GLIBC_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError creating %s.%s" \
+			printf "\\tError creating %s.\\n\\t%s\\n" \
 			"${GLIBC_TOOLCHAIN_SRCDIR}"/build "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 
 		cd "${GLIBC_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError changing directory to %s.%s" \
+			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${GLIBC_TOOLCHAIN_SRCDIR}"/build "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 	fi
@@ -1414,7 +1414,7 @@ second_pass_gcc ()
 
 		cd "${GCC_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError changing directory to %s.%s" \
+			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${GCC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 		exit 1
@@ -1424,13 +1424,13 @@ second_pass_gcc ()
 	else
 		mkdir -p "${GCC_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError creating %s.%s" \
+			printf "\\tError creating %s.\\n\\t%s\\n" \
 			"${GCC_TOOLCHAIN_SRCDIR}"/build "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 
 		cd "${GCC_TOOLCHAIN_SRCDIR}"/build || \
 		{
-			printf "\\tError changing directory to %s.%s" \
+			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${GCC_TOOLCHAIN_SRCDIR}"/build "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 	fi
