Improvements to config handling
A previous commit broke handling of loading a config
if the file already existed as the variable for the config
file path was not even specified. This is now fixed.

Additonal changes:

* Git branch selection now removed from config
as you cannot change branches later with --single-branch

* Config file is no longer removed after an unsuccessful build.

* Libdir is no longer added to config file, as this is
dangerous in the first place. This improved handling
no longer leaves the config file with any possible
duplicate variables.

* Simplified Gentoo sanity if statements

* Added simple sanity checks on config file

* Kernel bamp (BAMP IT AP)

If you discover any duplicate entries in your config file,
please file a bug report here:

https://github.com/NTULINUX/toolchain_builder/issues

Thank you!

Signed-off-by: Alec Ari <neotheuser@ymail.com>

diff --git a/toolchain_builder b/toolchain_builder
--- a/toolchain_builder
+++ b/toolchain_builder
@@ -77,7 +77,7 @@ user_defaults ()
 	TOOLCHAIN_BINDIR="${STARTDIR}/toolchain-bin"
 	TOOLCHAIN_PATCHDIR="${STARTDIR}/patches"
 	CORES=$(grep -c processor /proc/cpuinfo)
-	LINUX_VER="4.11.3"
+	LINUX_VER="4.11.6"
 	GMP_VER="6.1.2"
 	MPFR_VER="3.1.5"
 	MPC_VER="1.0.3"
@@ -91,6 +91,8 @@ user_defaults ()
 # End of user configuration
 #
 
+user_defaults
+
 #
 # DO NOT MODIFY: Edit only the ABOVE values instead.
 # You may modify the config file itself if you have already one.
@@ -99,7 +101,6 @@ user_defaults ()
 # Only called if $TOOLCHAIN_CONFIG not found or first run
 generate_config ()
 {
-	user_defaults
 	touch "${TOOLCHAIN_CONFIG}"
 
 	printf "# Automatically generated by NTU's toolchain builder
@@ -113,12 +114,8 @@ LINUX_VER=%s\n
 GMP_VER=%s
 MPFR_VER=%s
 MPC_VER=%s
-ISL_VER=%s\n
-BINUTILS_GIT_BRANCH=%s
-GLIBC_GIT_BRANCH=%s
-GCC_GIT_BRANCH=%s\n" "${CORES}" "${TOOLCHAIN_SRCDIR}" "${TOOLCHAIN_BINDIR}" "${TOOLCHAIN_PATCHDIR}" \
-"${LINUX_VER}" "${GMP_VER}" "${MPFR_VER}" "${MPC_VER}" "${ISL_VER}" \
-"${BINUTILS_GIT_BRANCH}" "${GLIBC_GIT_BRANCH}" "${GCC_GIT_BRANCH}" &> "${TOOLCHAIN_CONFIG}"
+ISL_VER=%s\n" "${CORES}" "${TOOLCHAIN_SRCDIR}" "${TOOLCHAIN_BINDIR}" "${TOOLCHAIN_PATCHDIR}" \
+"${LINUX_VER}" "${GMP_VER}" "${MPFR_VER}" "${MPC_VER}" "${ISL_VER}" &> "${TOOLCHAIN_CONFIG}"
 }
 
 #
@@ -301,14 +298,6 @@ else
 	if [[ $(ls /etc/env.d/gcc/config*) ]] ; then
 		printf "\tYes. Testing the build environment...\n"
 		GENTOO_TRUE=1
-	else
-		printf "\tNo, assuming working toolchain.\n"
-		GENERIC_TRUE=1
-		printf "\nGENERIC_TRUE=%s\n" "${GENERIC_TRUE}" >> "${TOOLCHAIN_CONFIG}"
-	fi
-
-	if [[ ${GENTOO_TRUE} == 1 ]] ; then
-		unset GENTOO_PASS
 		GCC_ENV_CONF=$(cat /etc/env.d/gcc/config*)
 		MAKE_PROFILE_TEST=$(ls -la /etc/portage/make.profile)
 		if [[ "${GCC_ENV_CONF}" == *vanilla || "${MAKE_PROFILE_TEST}" != *hardened* ]] ; then
@@ -325,8 +314,27 @@ else
 			printf "\tError detecting the build environment.%s" "${REPORT_BUG_EXIT}"
 			exit 1
 		fi
+	else
+		printf "\tNo, assuming working toolchain.\n"
+		GENERIC_TRUE=1
+		printf "\nGENERIC_TRUE=%s\n" "${GENERIC_TRUE}" >> "${TOOLCHAIN_CONFIG}"
 	fi
 fi
+
+	printf "\n\tPerforming basic sanity checks on %s.\n" "${TOOLCHAIN_CONFIG}"
+	if [[ -f "${TOOLCHAIN_CONFIG}" && -r "${TOOLCHAIN_CONFIG}" ]] ; then
+		printf "\t%s is a regular file and readable.\n" "${TOOLCHAIN_CONFIG}"
+		if [[ -n "${TOOLCHAIN_BINDIR}" ]] ; then
+			printf "\tInstallation directory is defined.\n"
+		else
+			printf "\tInstallation directory is invalid or undefined. Exiting.\n"
+			exit 1
+		fi
+	else
+		printf "\tError processing config file.%s" "${REPORT_BUG_EXIT}"
+		exit 1
+	fi
+	printf "\tAssuming everything else is ok.\n"
 }
 
 #
@@ -338,10 +346,10 @@ fi
 if [[ -d "${TOOLCHAIN_BINDIR}" && "${TOOLCHAIN_COMPLETE}" != 1 && "${DEVELOPER_MODE}" != 1 ]] ; then
 	printf "\n\t%s found.
 \tToolchain build hung up unexpectedly.\n
-\tDeleting %s and \n\t%s in 10 seconds.\n
+\tDeleting %s in 10 seconds.\n
 \tThis action cannot be undone!
 \tPress Control+C to cancel.
-\t10.\n" "${TOOLCHAIN_BINDIR}" "${TOOLCHAIN_BINDIR}" "${TOOLCHAIN_CONFIG}"
+\t10.\n" "${TOOLCHAIN_BINDIR}" "${TOOLCHAIN_BINDIR}"
 	sleep 1
 	printf "\t9.\n"
 	sleep 1
@@ -363,7 +371,6 @@ if [[ -d "${TOOLCHAIN_BINDIR}" && "${TOOLCHAIN_COMPLETE}" != 1 && "${DEVELOPER_M
 	sleep 1
 	printf "\tCleaning up...\n\n"
 	rm -rf "${TOOLCHAIN_BINDIR}"
-	rm -rf "${TOOLCHAIN_CONFIG}"
 	printf "\tFinished. Please restart the script.\n"
 	exit 0
 elif [[ -d "${TOOLCHAIN_BINDIR}" && "${TOOLCHAIN_COMPLETE}" == 1 ]] ; then
@@ -748,31 +755,27 @@ prepare_libdir()
 if [[ "${ARCH_UNAME}" == *64 ]] ; then
 	if [[ ! -d "${TOOLCHAIN_BINDIR}"/usr/lib64 ]] ; then
 
-	mkdir -p "${TOOLCHAIN_BINDIR}"/usr/lib64 || \
-	{
-		printf "\tError creating ${TOOLCHAIN_BINDIR}/usr/lib64.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
-	}
+		mkdir -p "${TOOLCHAIN_BINDIR}"/usr/lib64 || \
+		{
+			printf "\tError creating ${TOOLCHAIN_BINDIR}/usr/lib64.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		}
 
-	printf "\tSetting TOOLCHAIN_LIBDIR...\n"
-	TOOLCHAIN_LIBDIR="${TOOLCHAIN_BINDIR}/usr/lib64"
+		printf "\tSetting TOOLCHAIN_LIBDIR...\n"
+		TOOLCHAIN_LIBDIR="${TOOLCHAIN_BINDIR}/usr/lib64"
 
-	printf "\tCreating symlink...\n"
-	ln -sfv "${TOOLCHAIN_BINDIR}"/usr/lib64 "${TOOLCHAIN_BINDIR}"/usr/lib
-
-	printf "\nTOOLCHAIN_LIBDIR=%s" "${TOOLCHAIN_LIBDIR}" >> "${TOOLCHAIN_CONFIG}"
+		printf "\tCreating symlink...\n"
+		ln -sfv "${TOOLCHAIN_BINDIR}"/usr/lib64 "${TOOLCHAIN_BINDIR}"/usr/lib
 	fi
 elif [[ ${ARCH_UNAME} == *86 ]] ; then
 	if [[ ! -d ${TOOLCHAIN_BINDIR}/usr/lib ]] ; then
 
-	mkdir -p "${TOOLCHAIN_BINDIR}"/usr/lib || \
-	{
-		printf "\tError creating ${TOOLCHAIN_BINDIR}/usr/lib.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
-	}
+		mkdir -p "${TOOLCHAIN_BINDIR}"/usr/lib || \
+		{
+			printf "\tError creating ${TOOLCHAIN_BINDIR}/usr/lib.%s" "${REPORT_BUG_EXIT}" ; exit 1 ;
+		}
 
-	printf "\tSetting TOOLCHAIN_LIBDIR...\n"
-	TOOLCHAIN_LIBDIR="${TOOLCHAIN_BINDIR}/usr/lib"
-
-	printf "\nTOOLCHAIN_LIBDIR=%s" "${TOOLCHAIN_LIBDIR}" >> "${TOOLCHAIN_CONFIG}"
+		printf "\tSetting TOOLCHAIN_LIBDIR...\n"
+		TOOLCHAIN_LIBDIR="${TOOLCHAIN_BINDIR}/usr/lib"
 	fi
 fi
 }
