Minor adjustments and formatting changes
Signed-off-by: Alec Ari <neotheuser@ymail.com>

diff --git a/toolchain_builder b/toolchain_builder
--- a/toolchain_builder
+++ b/toolchain_builder
@@ -81,9 +81,9 @@ generate_defaults ()
 	GLIBC_GIT_BRANCH="master"
 	GCC_GIT_BRANCH="master"
 
-	printf "# Automatically generated by NTU's toolchain builder\n" &> ${TOOLCHAIN_CONFIG}
-	printf "# Please use care when modifying this file\n" >> ${TOOLCHAIN_CONFIG}
-	printf "# All paths must be absolute! \n" >> ${TOOLCHAIN_CONFIG}
+	printf "# Automatically generated by NTU's toolchain builder
+# Please use care when modifying this file
+# All paths must be absolute! \n" &> ${TOOLCHAIN_CONFIG}
 
 #
 # DO NOT MODIFY: Edit above values instead
@@ -165,7 +165,7 @@ else
 	fi
 	SYSTEM_OK=1
 	printf "\nARCH_UNAME=${ARCH_UNAME}\n" >> ${TOOLCHAIN_CONFIG}
-	printf "\nSYSTEM_OK="${SYSTEM_OK}"\n" >> ${TOOLCHAIN_CONFIG}
+	printf "\nSYSTEM_OK=${SYSTEM_OK}" >> ${TOOLCHAIN_CONFIG}
 fi
 
 # Probably not the BEST way to check, but it gets the job done
@@ -176,7 +176,8 @@ else
 	unset GENERIC_TRUE
 	printf "\n\tIs this a Gentoo system?\n"
 	if [[ `ls /etc/env.d/gcc/config*` ]] ; then
-		printf "\tYes. Testing the build environment...\n" && GENTOO_TRUE=1
+		printf "\tYes. Testing the build environment...\n"
+		GENTOO_TRUE=1
 	else
 		printf "\tNo, assuming working toolchain.\n"
 		GENERIC_TRUE=1
@@ -210,7 +211,7 @@ fi
 #
 
 # If complete toolchain already exists, do not clean
-# If interrupted, always restart
+# If interrupted, always do a fresh restart
 if [[ -d "${TOOLCHAIN_BINDIR}" && ${TOOLCHAIN_COMPLETE} != 1 && ${DEVELOPER_MODE} != 1 ]] ; then
 	printf "\n\t${TOOLCHAIN_BINDIR} found.\n\n"
 	printf "\tToolchain build hung up unexpectedly.\n"
@@ -293,9 +294,9 @@ GCC_GIT="git://gcc.gnu.org/git/gcc.git"
 LINUX_TOOLCHAIN_SRCDIR="${TOOLCHAIN_SRCDIR}/linux-${LINUX_VER}"
 LINUX_LOC="https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-${LINUX_VER}.tar.xz"
 
-GMP_LOC="https://ftp.gnu.org/gnu/gmp/gmp-${GMP_VER}.tar.xz"
+GMP_LOC="http://ftpmirror.gnu.org/gnu/gmp/gmp-${GMP_VER}.tar.xz"
 MPFR_LOC="http://www.mpfr.org/mpfr-current/mpfr-${MPFR_VER}.tar.xz"
-MPC_LOC="ftp://ftp.gnu.org/gnu/mpc/mpc-${MPC_VER}.tar.gz"
+MPC_LOC="http://ftpmirror.gnu.org/gnu/mpc/mpc-${MPC_VER}.tar.gz"
 ISL_LOC="http://isl.gforge.inria.fr/isl-${ISL_VER}.tar.xz"
 
 # Fixes stupid, highly annoying and also fatal, libstdc++-v3 PIC compiling error
@@ -547,30 +548,30 @@ if [[ ${ARCH_UNAME} == *64 ]] ; then
 	if [[ ! -d ${TOOLCHAIN_BINDIR}/usr/lib64 ]] ; then
 
 	mkdir -p ${TOOLCHAIN_BINDIR}/usr/lib64 || \
-	{ printf "\tError creating ${TOOLCHAIN_BINDIR}/usr/lib64. Exiting.\n" ; exit 1 ; }
+	{ printf "\tError creating ${TOOLCHAIN_BINDIR}/usr/lib64.${REPORT_BUG_EXIT}" ; exit 1 ; }
 
 	printf "\tSetting TOOLCHAIN_LIBDIR...\n"
 	TOOLCHAIN_LIBDIR="${TOOLCHAIN_BINDIR}/usr/lib64"
-	printf "\nTOOLCHAIN_LIBDIR=${TOOLCHAIN_LIBDIR}\n" >> ${TOOLCHAIN_CONFIG}
 
 	printf "\tCreating symlink...\n"
 	ln -sfv ${TOOLCHAIN_BINDIR}/usr/lib64 ${TOOLCHAIN_BINDIR}/usr/lib
 
 	LIBDIR_SET=1
-	printf "LIBDIR_SET=${LIBDIR_SET}\n" >> ${TOOLCHAIN_CONFIG}
+	printf "\nTOOLCHAIN_LIBDIR=${TOOLCHAIN_LIBDIR}" >> ${TOOLCHAIN_CONFIG}
+	printf "\nLIBDIR_SET=${LIBDIR_SET}\n" >> ${TOOLCHAIN_CONFIG}
 	fi
 elif [[ ${ARCH_UNAME} == *86 ]] ; then
-	if [[ ! -d ${TOOLCHAIN_BINDIR}/usr/lib64 ]] ; then
+	if [[ ! -d ${TOOLCHAIN_BINDIR}/usr/lib ]] ; then
 
 	mkdir -p ${TOOLCHAIN_BINDIR}/usr/lib || \
-	{ printf "\tError creating ${TOOLCHAIN_BINDIR}/usr/lib. Exiting.\n" ; exit 1 ; }
+	{ printf "\tError creating ${TOOLCHAIN_BINDIR}/usr/lib.${REPORT_BUG_EXIT}" ; exit 1 ; }
 
 	printf "\tSetting TOOLCHAIN_LIBDIR...\n"
 	TOOLCHAIN_LIBDIR="${TOOLCHAIN_BINDIR}/usr/lib"
-	printf "\nTOOLCHAIN_LIBDIR=${TOOLCHAIN_LIBDIR}\n" >> ${TOOLCHAIN_CONFIG}
 
 	LIBDIR_SET=1
-	printf "LIBDIR_SET=${LIBDIR_SET}\n" >> ${TOOLCHAIN_CONFIG}
+	printf "\nTOOLCHAIN_LIBDIR=${TOOLCHAIN_LIBDIR}" >> ${TOOLCHAIN_CONFIG}
+	printf "\nLIBDIR_SET=${LIBDIR_SET}\n" >> ${TOOLCHAIN_CONFIG}
 	fi
 fi
 }
@@ -642,8 +643,6 @@ elif [[ $? == 1 ]] ; then
 
 	sed "s#/lib64/ld-linux-x86-64.so.2#${TOOLCHAIN_LIBDIR}/ld-linux-x86-64.so.2#g" -i ${X86_64_LDCONFIG} || \
 	{ printf "\tApplying hard code fix (64) failed.${REPORT_BUG_EXIT}" ; exit 1 ; }
-
-
 
 	printf "\tGLIBC hard code fix now applied.\n"
 else
@@ -846,6 +845,7 @@ fi
 
 	make -j${CORES} || \
 	{ printf "\n\tBinutils compile error. Exiting.\n" ; exit 1 ; }
+
 	make install || \
 	{ printf "\n\tBinutils install error. Exiting.\n" ; exit 1 ; }
 }
@@ -994,6 +994,8 @@ fi
 
 	# Eliminates the need for 500 lines here
 	printf "\n\tUpdating PATH var...\n"
+	unset ORIG_PATH
+	unset NEW_PATH
 	ORIG_PATH="$PATH"
 	NEW_PATH="${TOOLCHAIN_BINDIR}/usr/bin:$PATH"
 	PATH="${NEW_PATH}"
@@ -1016,6 +1018,7 @@ fi
 
 	make -j${CORES} || \
 	{ printf "\n\tBinutils compile error. Exiting.\n" ; exit 1 ; }
+
 	make install || \
 	{ printf "\n\tBinutils install error. Exiting.\n" ; exit 1 ; }
 }
@@ -1145,14 +1148,13 @@ build_toolchain ()
 
 	second_pass_gcc
 
-	printf "\n\tToolchain built successfully! \n"
-	printf "\n\tTo add the toolchain to your PATH, simply run the following: \n"
-	printf "\texport PATH=${TOOLCHAIN_BINDIR}/usr/bin:$PATH\n"
-	printf "\n\tTo make sure your new toolchain is in use, run: \n"
-	printf "\t'ld --version' or 'gcc --version' without quotes.\n"
-
-	printf "\n\tIf you would like to use the Gold linker by default,
-\tRun the following:\n
+	printf "\n\tToolchain built successfully! \n
+\tTo add the toolchain to your PATH, simply run the following:
+\texport PATH=${TOOLCHAIN_BINDIR}/usr/bin:${ORIG_PATH}\n
+\tThen to make sure your new toolchain is in use, run:
+\t'ld --version' and 'gcc --version' without quotes.\n
+\tIf you would like to use the Gold linker by default,
+\tRun the following:
 \tln -sfv ${TOOLCHAIN_BINDIR}/usr/bin/ld.gold ln -sfv ${TOOLCHAIN_BINDIR}/usr/bin/ld\n"
 
 	TOOLCHAIN_COMPLETE=1
