Various updates
Update package versions, trim LOC footprint,
and further adjust config handling. Also,
re-work patch handling and make things less ugly.

Signed-off-by: Alec Ari <neotheuser@ymail.com>

diff --git a/toolchain_builder b/toolchain_builder
--- a/toolchain_builder
+++ b/toolchain_builder
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# Copyright (C) 2016 - 2017 Alec Ari <neotheuser@ymail.com>
+# Copyright (C) 2016 - 2018 Alec Ari <neotheuser@ymail.com>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -15,13 +15,9 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# TODO: Possible long-term reach goal: Create a small chroot environment using git toolchain
-# May be necessary as GLIBC has hard codes set that I cannot find via git grep
-# Gentoo prefix development team may have some answers
-
 # printf because this is now a C program
 printf "\\n\\tNTU's complete bleeding edge native x86/amd64 toolchain builder
-\\tCopyright (C) 2016 - 2017 Alec Ari\\n"
+\\tCopyright (C) 2016 - 2018 Alec Ari\\n"
 sleep 3
 
 # This is here to ensure we don't accidentally break something bad
@@ -51,87 +47,36 @@ fi
 # Reduce lengthly printf lines
 REPORT_BUG_EXIT="Please report bug to script maintainer. Exiting."
 
-#
-# User configuation:
-# You may modify these default settings before running this script to your liking
-#
+TOOLCHAIN_INTERNAL_CONFIG="${STARTDIR}/toolchain_internal.config"
+TOOLCHAIN_USER_CONFIG="${STARTDIR}/toolchain_user.config"
 
-user_defaults ()
-{
-	unset TOOLCHAIN_CONFIG
-	unset TOOLCHAIN_SRCDIR
-	unset TOOLCHAIN_BINDIR
-	unset TOOLCHAIN_PATCHDIR
-	unset CORES
-	unset LINUX_VER
-	unset GMP_VER
-	unset MPFR_VER
-	unset MPC_VER
-	unset ISL_VER
-	unset BINUTILS_GIT_BRANCH
-	unset GLIBC_GIT_BRANCH
-	unset GCC_GIT_BRANCH
-
-	TOOLCHAIN_CONFIG="${STARTDIR}/toolchain_builder.config"
-	TOOLCHAIN_SRCDIR="${STARTDIR}/toolchain-src"
-	TOOLCHAIN_BINDIR="${STARTDIR}/toolchain-bin"
-	TOOLCHAIN_PATCHDIR="${STARTDIR}/patches"
-	CORES=$(grep -c processor /proc/cpuinfo)
-	LINUX_VER="4.12.4"
-	GMP_VER="6.1.2"
-	MPFR_VER="3.1.5"
-	MPC_VER="1.0.3"
-	ISL_VER="0.18"
-	BINUTILS_GIT_BRANCH="master"
-	GLIBC_GIT_BRANCH="master"
-	GCC_GIT_BRANCH="master"
-}
-
-#
-# End of user configuration
-#
-
-user_defaults
-
-#
-# DO NOT MODIFY: Edit only the ABOVE values instead.
-# You may modify the config file itself if you have already one.
-#
-
-# Only called if $TOOLCHAIN_CONFIG not found or first run
-generate_config ()
-{
-	touch "${TOOLCHAIN_CONFIG}"
-
-	printf "# Automatically generated by NTU's toolchain builder
-# Please use care when modifying this file
-# All paths must be absolute! \\n
-CORES=%s\\n
-TOOLCHAIN_SRCDIR=%s
-TOOLCHAIN_BINDIR=%s
-TOOLCHAIN_PATCHDIR=%s\\n
-LINUX_VER=%s\\n
-GMP_VER=%s
-MPFR_VER=%s
-MPC_VER=%s
-ISL_VER=%s\\n" "${CORES}" "${TOOLCHAIN_SRCDIR}" "${TOOLCHAIN_BINDIR}" "${TOOLCHAIN_PATCHDIR}" \
-"${LINUX_VER}" "${GMP_VER}" "${MPFR_VER}" "${MPC_VER}" "${ISL_VER}" &> "${TOOLCHAIN_CONFIG}"
-}
-
-#
-# End of editing notice
-#
-
-# Load config if present, generate if not
-printf "\\n\\tChecking for pre-existing config file...\\n"
-if [[ -f "${TOOLCHAIN_CONFIG}" ]] ; then
+# Load user config if present, error out if not
+printf "\\n\\tChecking for pre-existing user config file...\\n"
+if [[ -f "${TOOLCHAIN_USER_CONFIG}" ]] ; then
 	printf "\\tConfig file found. Loading...\\n"
 	# shellcheck source=/dev/null
-	source "${TOOLCHAIN_CONFIG}"
+	source "${TOOLCHAIN_USER_CONFIG}"
 	printf "\\tLoaded.\\n"
 else
-	printf "\\tConfig file not found. Creating one.\\n"
-	generate_config
+	printf "\\tError: User config file not found. Exiting.\\n"
+	exit 1
+fi
+
+# You shouldn't (need to) modify these
+TOOLCHAIN_SRCDIR="${STARTDIR}/toolchain-src"
+TOOLCHAIN_BINDIR="${STARTDIR}/toolchain-bin"
+TOOLCHAIN_PATCHDIR="${STARTDIR}/patches"
+
+# Load internal config if present, generate one if not
+printf "\\n\\tChecking for pre-existing internal config file...\\n"
+if [[ -f "${TOOLCHAIN_INTERNAL_CONFIG}" ]] ; then
+	printf "\\tConfig file found. Loading...\\n"
+	# shellcheck source=/dev/null
+	source "${TOOLCHAIN_INTERNAL_CONFIG}"
+	printf "\\tLoaded.\\n"
+else
+	printf "\\tGenerating internal config file...\\n"
+	printf "# Automatically generated file; Please edit with caution.\\n\\n" &> "${TOOLCHAIN_INTERNAL_CONFIG}"
 fi
 
 #
@@ -272,7 +217,6 @@ else
 # See function check_ld_linker_path for more info
 # I'm also not interested in testing this on other architectures
 	printf "\\n\\tDetecting kernel bitness...\\n"
-	unset ARCH_UNAME
 	ARCH_UNAME=$(uname -m)
 	if [[ ${ARCH_UNAME} == *64 ]] ; then
 		printf "\\t64-bit\\n"
@@ -284,16 +228,14 @@ else
 		exit 1
 	fi
 	SYSTEM_OK=1
-	printf "\\nARCH_UNAME=%s\\n" "${ARCH_UNAME}" >> "${TOOLCHAIN_CONFIG}"
-	printf "\\nSYSTEM_OK=%s" "${SYSTEM_OK}" >> "${TOOLCHAIN_CONFIG}"
+	printf 'ARCH_UNAME="%s"\n' "${ARCH_UNAME}" >> "${TOOLCHAIN_INTERNAL_CONFIG}"
+	printf '\nSYSTEM_OK="%s"\n' "${SYSTEM_OK}" >> "${TOOLCHAIN_INTERNAL_CONFIG}"
 fi
 
 # Definitely not the best way to check, but it works
 if [[ "${GENTOO_PASS}" == 1 || "${GENERIC_TRUE}" == 1 ]] ; then
 	printf "\\n\\tSystem already passed compiler check.\\n"
 else
-	unset GENTOO_PASS
-	unset GENERIC_TRUE
 	printf "\\n\\tIs this a Gentoo system?\\n"
 	if [[ $(ls /etc/env.d/gcc/config*) ]] ; then
 		printf "\\tYes. Testing the build environment...\\n"
@@ -301,8 +243,8 @@ else
 		MAKE_PROFILE_TEST=$(ls -la /etc/portage/make.profile)
 		if [[ "${GCC_ENV_CONF}" == *vanilla || "${MAKE_PROFILE_TEST}" != *hardened* ]] ; then
 			printf "\\tGood, vanilla toolchain.\\n"
-			GENTOO_PASS=1
-			printf "\\nGENTOO_PASS=%s\\n" "${GENTOO_PASS}" >> "${TOOLCHAIN_CONFIG}"
+			GENTOO_PASS="1"
+			printf '\nGENTOO_PASS="%s"\n' "${GENTOO_PASS}" >> "${TOOLCHAIN_INTERNAL_CONFIG}"
 		elif [[ "${MAKE_PROFILE_TEST}" == *hardened* ]] ; then
 			printf "\\tNot vanilla GCC, this may cause a GCC build failure
 \\tas -fPIC and potentially other CFLAGS are known to issues.
@@ -315,25 +257,10 @@ else
 		fi
 	else
 		printf "\\tNo, assuming working toolchain.\\n"
-		GENERIC_TRUE=1
-		printf "\\nGENERIC_TRUE=%s\\n" "${GENERIC_TRUE}" >> "${TOOLCHAIN_CONFIG}"
+		GENERIC_TRUE="1"
+		printf '\nGENERIC_TRUE="%s"\n' "${GENERIC_TRUE}" >> "${TOOLCHAIN_INTERNAL_CONFIG}"
 	fi
 fi
-
-	printf "\\n\\tPerforming basic sanity checks on %s.\\n" "${TOOLCHAIN_CONFIG}"
-	if [[ -f "${TOOLCHAIN_CONFIG}" && -r "${TOOLCHAIN_CONFIG}" ]] ; then
-		printf "\\t%s is a regular file and readable.\\n" "${TOOLCHAIN_CONFIG}"
-		if [[ -n "${TOOLCHAIN_BINDIR}" ]] ; then
-			printf "\\tInstallation directory is defined.\\n"
-		else
-			printf "\\tInstallation directory is invalid or undefined. Exiting.\\n"
-			exit 1
-		fi
-	else
-		printf "\\tError processing config file.\\n\\t%s\\n" "${REPORT_BUG_EXIT}"
-		exit 1
-	fi
-	printf "\\tAssuming everything else is ok.\\n"
 }
 
 #
@@ -375,7 +302,7 @@ if [[ -d "${TOOLCHAIN_BINDIR}" && "${TOOLCHAIN_COMPLETE}" != 1 && "${DEVELOPER_M
 elif [[ -d "${TOOLCHAIN_BINDIR}" && "${TOOLCHAIN_COMPLETE}" == 1 ]] ; then
 	printf "\\n\\tToolchain already built.\\n
 \\t%s and\\n\\t%s must be manually removed to proceed.
-\\tNothing to do. Exiting.\\n" "${TOOLCHAIN_BINDIR}" "${TOOLCHAIN_CONFIG}"
+\\tNothing to do. Exiting.\\n" "${TOOLCHAIN_BINDIR}" "${TOOLCHAIN_INTERNAL_CONFIG}"
 	exit 0
 fi
 
@@ -383,30 +310,6 @@ fi
 unset CFLAGS
 unset CXXFLAGS
 unset LDFLAGS
-
-unset LINUX_TOOLCHAIN_SRCDIR
-unset BINUTILS_TOOLCHAIN_SRCDIR
-unset GLIBC_TOOLCHAIN_SRCDIR
-unset GCC_TOOLCHAIN_SRCDIR
-unset GMP_TOOLCHAIN_SRCDIR
-unset MPFR_TOOLCHAIN_SRCDIR
-unset MPC_TOOLCHAIN_SRCDIR
-unset ISL_TOOLCHAIN_SRCDIR
-
-unset BINUTILS_GIT
-unset GLIBC_GIT
-unset GCC_GIT
-
-unset BINUTILS_GIT_OPTS
-unset GLIBC_GIT_OPTS
-unset GCC_GIT_OPTS
-
-unset LINUX_LOC
-unset GMP_LOC
-unset MPFR_LOC
-unset MPC_LOC
-unset ISL_LOC
-unset GCC_PIC_PATCH
 
 #
 # DO NOT MODIFY
@@ -459,25 +362,21 @@ fetch_sources ()
 
 	printf "\\n\\tFetching sources if needed...\\n"
 
-	# Binutils sources
 if [[ ! -d "${BINUTILS_TOOLCHAIN_SRCDIR}" ]] ; then
 	printf "\\n\\tFetching Binutils via git...\\n"
 	git clone "${BINUTILS_GIT_OPTS[@]}" "${BINUTILS_GIT}" "${BINUTILS_TOOLCHAIN_SRCDIR}"
 fi
 
-	# GLIBC sources
 if [[ ! -d "${GLIBC_TOOLCHAIN_SRCDIR}" ]] ; then
 	printf "\\n\\tFetching GLIBC via git...\\n"
 	git clone "${GLIBC_GIT_OPTS[@]}" "${GLIBC_GIT}" "${GLIBC_TOOLCHAIN_SRCDIR}"
 fi
 
-	# GCC sources
 if [[ ! -d "${GCC_TOOLCHAIN_SRCDIR}" ]] ; then
 	printf "\\n\\tFetching GCC via git...\\n"
 	git clone "${GCC_GIT_OPTS[@]}" "${GCC_GIT}" "${GCC_TOOLCHAIN_SRCDIR}"
 fi
 
-	# Linux sources
 if [[ ! -f "${TOOLCHAIN_SRCDIR}"/linux-"${LINUX_VER}".tar.xz ]] ; then
 	printf "\\n\\tDownloading Linux sources via wget...\\n"
 	wget -c "${LINUX_LOC}" || \
@@ -487,7 +386,6 @@ if [[ ! -f "${TOOLCHAIN_SRCDIR}"/linux-"${LINUX_VER}".tar.xz ]] ; then
 	}
 fi
 
-	# GMP sources
 if [[ ! -f "${TOOLCHAIN_SRCDIR}"/gmp-"${GMP_VER}".tar.xz ]] ; then
 	printf "\\tDownloading GMP via wget...\\n"
 	wget -c ${GMP_LOC} || \
@@ -497,7 +395,6 @@ if [[ ! -f "${TOOLCHAIN_SRCDIR}"/gmp-"${GMP_VER}".tar.xz ]] ; then
 	}
 fi
 
-	# MPFR sources
 if [[ ! -f "${TOOLCHAIN_SRCDIR}"/mpfr-"${MPFR_VER}".tar.xz ]] ; then
 	printf "\\tDownloading MPFR via wget...\\n"
 	wget -c ${MPFR_LOC} || \
@@ -507,7 +404,6 @@ if [[ ! -f "${TOOLCHAIN_SRCDIR}"/mpfr-"${MPFR_VER}".tar.xz ]] ; then
 	}
 fi
 
-	# MPC sources
 if [[ ! -f "${TOOLCHAIN_SRCDIR}"/mpc-"${MPC_VER}".tar.gz ]] ; then
 	printf "\\tDownloading MPC via wget...\\n"
 	wget -c ${MPC_LOC} || \
@@ -517,7 +413,6 @@ if [[ ! -f "${TOOLCHAIN_SRCDIR}"/mpc-"${MPC_VER}".tar.gz ]] ; then
 	}
 fi
 
-	# ISL sources
 if [[ ! -f "${TOOLCHAIN_SRCDIR}"/isl-"${ISL_VER}".tar.xz ]] ; then
 	printf "\\tDownloading ISL via wget...\\n"
 	wget -c ${ISL_LOC} || \
@@ -635,9 +530,10 @@ verify_sources ()
 
 #
 # End of verify sources
+#
 
 #
-# Update git repositories
+# Update git sources
 #
 
 # We only clone a single branch, so changing branches later will not work
@@ -700,7 +596,7 @@ fi
 }
 
 #
-# End of update sources
+# End of update git sources
 #
 
 init_toolchain_srcdir ()
@@ -743,10 +639,8 @@ main ()
 # This is where the building starts
 #
 
-#
-# Create lib64 and a lib symlink to it if 64-bit
-#
-
+# Create lib64 dir and a lib symlink to it if 64-bit,
+# otherwise just make lib dir.
 prepare_libdir()
 {
 	printf "\\n\\tPreparing toolchain libdir...\\n"
@@ -755,7 +649,8 @@ if [[ "${ARCH_UNAME}" == *64 ]] ; then
 
 		mkdir -p "${TOOLCHAIN_BINDIR}"/usr/lib64 || \
 		{
-			printf "\\tError creating ${TOOLCHAIN_BINDIR}/usr/lib64.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
+			printf "\\tError creating ${TOOLCHAIN_BINDIR}/usr/lib64.\\n\\t%s\\n" \
+			"${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 
 		printf "\\tSetting TOOLCHAIN_LIBDIR...\\n"
@@ -769,7 +664,8 @@ elif [[ ${ARCH_UNAME} == *86 ]] ; then
 
 		mkdir -p "${TOOLCHAIN_BINDIR}"/usr/lib || \
 		{
-			printf "\\tError creating ${TOOLCHAIN_BINDIR}/usr/lib.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
+			printf "\\tError creating ${TOOLCHAIN_BINDIR}/usr/lib.\\n\\t%s\\n" \
+			"${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
 
 		printf "\\tSetting TOOLCHAIN_LIBDIR...\\n"
@@ -778,14 +674,7 @@ elif [[ ${ARCH_UNAME} == *86 ]] ; then
 fi
 }
 
-#
-# End of possible lib symlink to lib64
-#
-
-#
-# Prepare Binutils
-#
-
+# Copy MPC, MPFR, GMP and ISL to Binutils srcdir
 prepare_binutils ()
 {
 	printf "\\n\\tCopying required libraries to Binutils if needed.\\n"
@@ -826,25 +715,15 @@ if [[ ! -d ${BINUTILS_TOOLCHAIN_SRCDIR}/isl ]] ; then
 fi
 }
 
-#
-# End of Binutils preparation
-#
-
-#
 # GLIBC hard code fix
-#
-
-# Suggestions welcome on a better way to do this (very ugly)
 check_glibc_hardcode ()
 {
 	X86_64_LDCONFIG="${GLIBC_TOOLCHAIN_SRCDIR}/sysdeps/unix/sysv/linux/x86_64/ldconfig.h"
 
-	printf "\\n\\tIs GLIBC hard coded?\\n"
-
+if [[ "${GLIBC_HARDCODE_FIXED}" == "1" ]] ; then
+	printf "\\tGLIBC hard code fix already applied.\\n"
+else
 	# Change hard link from /{lib,lib64} to $TOOLCHAIN_LIBDIR
-if [[ $(grep -c "${TOOLCHAIN_LIBDIR}" "${X86_64_LDCONFIG}") == 1 ]] ; then
-	printf "\\tYes. GLIBC hard code fix already applied.\\n"
-elif [[ $(grep -c "${TOOLCHAIN_LIBDIR}" "${X86_64_LDCONFIG}") == 0 ]] ; then
 	printf "\\tGLIBC hard code fix not applied, attempting to fix via sed...\\n"
 
 	sed "s#/lib/ld-linux.so.2#${TOOLCHAIN_LIBDIR}/ld-linux.so.2#g" -i "${X86_64_LDCONFIG}" || \
@@ -858,100 +737,63 @@ elif [[ $(grep -c "${TOOLCHAIN_LIBDIR}" "${X86_64_LDCONFIG}") == 0 ]] ; then
 	}
 
 	printf "\\tGLIBC hard code fix now applied.\\n"
-else
-	printf "\\tError detecting if GLIBC is hard coded.\\n\\t%s\\n" "${REPORT_BUG_EXIT}"
-	exit 1
+	GLIBC_HARDCODE_FIXED="1"
+	printf '\nGLIBC_HARDCODE_FIXED="%s"\n' "${GLIBC_HARDCODE_FIXED}" >> "${TOOLCHAIN_INTERNAL_CONFIG}"
 fi
 }
-
-#
-# End of GLIBC hard code fix
 
 #
 # Prepare GCC
 #
 
-# Not a good way to check if GCC is patched
 # May break with future GCC updates
-# Works for now, suggestions welcome
 # Fixes GCC bug #58638
 check_gcc_pic_patch ()
 {
-	printf "\\n\\tChecking if gcc/libstdc++-v3 is already patched...\\n"
+if [[ "${GCC_PIC_PATCH_APPLIED}" == "1" ]] ; then
+	printf "\\tlibstdc++-v3 PIC patch already applied.\\n"
+else
+	printf "\\tApplying libstdc++-v3 PIC patch...\\n"
 
-	PIC_CONF_NUM="$(grep -c 'glibcxx_lt_pic_flag="-prefer-pic"' \
-	"${GCC_TOOLCHAIN_SRCDIR}"/libstdc++-v3/configure)"
-
-	PIC_CONF_AC_NUM="$(grep -c 'glibcxx_lt_pic_flag="-prefer-pic"' \
-	"${GCC_TOOLCHAIN_SRCDIR}"/libstdc++-v3/configure.ac)"
-
-if [[ ${PIC_CONF_NUM} == 1 && ${PIC_CONF_AC_NUM} == 1 ]] ; then
-	printf "\\tlibstdc++-v3 PIC patch not applied. Applying...\\n"
-
-	cd "${GLIBC_TOOLCHAIN_SRCDIR}" || \
-	printf "\\tError changing directory to %s.\\n\\t%s\\n" \
-	"${GLIBC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" \
-	exit 1
+	cd "${GCC_TOOLCHAIN_SRCDIR}" || \
+	{
+		printf "\\tError changing directory to %s.\\n\\t%s\\n" \
+		"${GCC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
+	}
 
 	patch -p1 < "${GCC_PIC_PATCH}" || \
 	{
 		printf "\\tlibstdc++-v3 PIC patch failed.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
-elif [[ "${PIC_CONF_NUM}" == 2 && "${PIC_CONF_AC_NUM}" == 2 ]] ; then
-	printf "\\tlibstdc++-v3 PIC patch already applied.\\n"
-else
-	printf "\\tgcc/libstdc++-v3 patch failed.\\n\\t%s\\n" "${REPORT_BUG_EXIT}"
-	exit 1
+	printf "\\tlibstdc++-v3 PIC patch now applied.\\n"
+	GCC_PIC_PATCH_APPLIED="1"
+	printf '\nGCC_PIC_PATCH_APPLIED="%s"\n' "${GCC_PIC_PATCH_APPLIED}" >> "${TOOLCHAIN_INTERNAL_CONFIG}"
 fi
 }
 
-# Suggestions welcome on a better way to do this (very ugly)
 check_ld_linker_path ()
 {
 	GCC_CONF_32_H="${GCC_TOOLCHAIN_SRCDIR}/gcc/config/i386/linux.h"
 	GCC_CONF_64_H="${GCC_TOOLCHAIN_SRCDIR}/gcc/config/i386/linux64.h"
 
-	printf "\\n\\tIs GCC using the proper linker?\\n"
-
-	# This changes GCC's hard link from /lib/ld-linux-so.2 to $TOOLCHAIN_LIBDIR/ld-linux.so.2
-if [[ $(grep -c "${TOOLCHAIN_LIBDIR}" "${GCC_CONF_32_H}") == 1 ]] ; then
-	printf "\\tYes. 32-bit GCC linker fix already applied.\\n"
-elif [[ $(grep -c "${TOOLCHAIN_LIBDIR}" "${GCC_CONF_32_H}") == 0 ]] ; then
-	printf "\\t32-bit GCC linker fix not applied, attempting to fix via sed...\\n"
-
+if [[ "${LD_LINKER_PATH_FIXED}" == "1" ]] ; then
+	printf "\\tGCC linker fix already applied.\\n"
+else
+	printf "\\tApplying GCC linker fix...\\n"
 	sed "s#/lib/ld-linux.so.2#${TOOLCHAIN_LIBDIR}/ld-linux.so.2#g" -i "${GCC_CONF_32_H}" || \
 	{
 		printf "\\tApplying 32-bit linker fix failed.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
-
-	printf "\\t32-bit GCC linker fix now applied.\\n"
-else
-	printf "\\tError detecting if GCC is using proper linker.\\n\\t%s\\n" "${REPORT_BUG_EXIT}"
-	exit 1
-fi
-
-	# 64-bit hard link fix
-	# This changes GCC's hard link from /lib/ld-linux-x86-64.so.2 to $TOOLCHAIN_LIBDIR/ld-linux-x86-64.so.2
-if [[ $(grep -c "${TOOLCHAIN_LIBDIR}" "${GCC_CONF_64_H}") == 1 ]] ; then
-	printf "\\tYes. 64-bit GCC linker fix already applied.\\n"
-elif [[ $(grep -c "${TOOLCHAIN_LIBDIR}" "${GCC_CONF_64_H}") == 0 ]] ; then
-	printf "\\t64-bit GCC linker fix not applied, attempting to fix via sed...\\n"
 
 	sed "s#/lib64/ld-linux-x86-64.so.2#${TOOLCHAIN_LIBDIR}/ld-linux-x86-64.so.2#g" -i "${GCC_CONF_64_H}" || \
 	{
 		printf "\\tApplying 64-bit linker fix failed.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
 	}
 
-	sed "s#/lib/ld-linux.so.2#${TOOLCHAIN_LIBDIR}/ld-linux.so.2#g" -i "${GCC_CONF_64_H}" || \
-	{
-		printf "\\tApplying 64-bit linker fix failed.\\n\\t%s\\n" "${REPORT_BUG_EXIT}" ; exit 1 ;
-	}
-
-	printf "\\t64-bit GCC linker fix now applied.\\n"
-else
-	printf "\\tError detecting if GCC is using proper linker.\\n\\t%s\\n" "${REPORT_BUG_EXIT}"
-	exit 1
+	LD_LINKER_PATH_FIXED="1"
+	printf '\nLD_LINKER_PATH_FIXED="%s"\n' "${LD_LINKER_PATH_FIXED}" >> "${TOOLCHAIN_INTERNAL_CONFIG}"
+	printf "\\tGCC linker fixes now applied.\\n"
 fi
 }
 
@@ -1124,7 +966,6 @@ first_pass_glibc ()
 			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${GLIBC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
-		exit 1
 
 		make distclean
 		rm -rf "${GLIBC_TOOLCHAIN_SRCDIR}"/build/*
@@ -1184,7 +1025,6 @@ first_pass_gcc ()
 			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${GCC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
-		exit 1
 
 		make distclean
 		rm -rf "${GCC_TOOLCHAIN_SRCDIR}"/build/*
@@ -1280,7 +1120,6 @@ second_pass_binutils ()
 			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${BINUTILS_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
-		exit 1
 
 		make distclean
 		rm -rf "${BINUTILS_TOOLCHAIN_SRCDIR}"/build/*
@@ -1300,10 +1139,8 @@ second_pass_binutils ()
 
 	# Eliminates the need for 500 lines here
 	printf "\\n\\tUpdating PATH var...\\n"
-	unset ORIG_PATH
-	unset NEW_PATH
-	ORIG_PATH="$PATH"
-	NEW_PATH="${TOOLCHAIN_BINDIR}/usr/bin:$PATH"
+	ORIG_PATH="${PATH}"
+	NEW_PATH="${TOOLCHAIN_BINDIR}/usr/bin:${PATH}"
 	PATH="${NEW_PATH}"
 	printf "\\tPATH now has new toolchain set first.\\n"
 
@@ -1417,7 +1254,6 @@ second_pass_gcc ()
 			printf "\\tError changing directory to %s.\\n\\t%s\\n" \
 			"${GCC_TOOLCHAIN_SRCDIR}" "${REPORT_BUG_EXIT}" ; exit 1 ;
 		}
-		exit 1
 
 		make distclean
 		rm -rf "${GCC_TOOLCHAIN_SRCDIR}"/build/*
@@ -1491,18 +1327,18 @@ build_toolchain ()
 
 	second_pass_gcc
 
-	printf "\\n\\tToolchain built successfully! \\n
-\\tTo add the toolchain to your PATH, simply run the following:
-\\texport PATH=%s/usr/bin:%s\\n
-\\tThen to make sure your new toolchain is in use, run:
-\\t'ld --version' and 'gcc --version' without quotes.\\n
-\\tIf you would like to use the Gold linker by default,
-\\tRun the following:
-\\tln -sfv %s/usr/bin/ld.gold %s/usr/bin/ld\\n" \
+	printf '\n\tToolchain built successfully! \n
+\tTo add the toolchain to your PATH, simply run the following:
+\texport PATH="%s/usr/bin:%s"\n
+\tThen to make sure your new toolchain is in use, run:
+\t"ld --version" and "gcc --version" without quotes.\\n
+\tIf you would like to use the Gold linker by default,
+\tRun the following:
+\tln -sfv %s/usr/bin/ld.gold %s/usr/bin/ld\n' \
 	"${TOOLCHAIN_BINDIR}" "${ORIG_PATH}" "${TOOLCHAIN_BINDIR}" "${TOOLCHAIN_BINDIR}"
 
 	TOOLCHAIN_COMPLETE=1
-	printf "\\nTOOLCHAIN_COMPLETE=%s\\n" "${TOOLCHAIN_COMPLETE}" >> "${TOOLCHAIN_CONFIG}"
+	printf '\nTOOLCHAIN_COMPLETE="%s"\n' "${TOOLCHAIN_COMPLETE}" >> "${TOOLCHAIN_INTERNAL_CONFIG}"
 }
 
 main
